Progra-Avanzada-Proyecto/Progra-Avanzada-Proyecto/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Progra_Avanzada_Proyecto.Models; 

namespace Progra_Avanzada_Proyecto.Controllers
{
    public class EventosController : Controller
    {
        private HttpClient httpClient = new HttpClient();

        public EventosController()
        {
            
            httpClient.BaseAddress = new Uri("https://localhost:44356/api/");
        }

        // GET: Eventos
        public async Task<ActionResult> Index()
        {
            var response = await httpClient.GetAsync("api/Eventos");
            if (response.IsSuccessStatusCode)
            {
                var eventos = await response.Content.ReadAsAsync<IEnumerable<EmpleadosViewModel>>();
                return View(eventos);
            }
            return View("Error");
        }

        // GET: Eventos/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var response = await httpClient.GetAsync($"api/Eventos/{id}");
            if (response.IsSuccessStatusCode)
            {
                var evento = await response.Content.ReadAsAsync<EmpleadosViewModel>();
                return View(evento);
            }
            return HttpNotFound();
        }

        // GET: Eventos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Eventos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmpleadosViewModel evento)
        {
            if (ModelState.IsValid)
            {
                var response = await httpClient.PostAsJsonAsync("api/Eventos", evento);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(evento);
        }

        // GET: Eventos/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var response = await httpClient.GetAsync($"api/Eventos/{id}");
            if (response.IsSuccessStatusCode)
            {
                var evento = await response.Content.ReadAsAsync<EmpleadosViewModel>();
                return View(evento);
            }
            return HttpNotFound();
        }

        // POST: Eventos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, EmpleadosViewModel evento)
        {
            if (ModelState.IsValid)
            {
                var response = await httpClient.PutAsJsonAsync($"api/Eventos/{id}", evento);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var response = await httpClient.GetAsync($"api/Eventos/{id}");
            if (response.IsSuccessStatusCode)
            {
                var evento = await response.Content.ReadAsAsync<EmpleadosViewModel>();
                return View(evento);
            }
            return HttpNotFound();
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var response = await httpClient.DeleteAsync($"api/Eventos/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
    }
}

Progra-Avanzada-Proyecto/Progra-Avanzada-Proyecto/Controllers/InventarioController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Progra_Avanzada_Proyecto.Models;
using System.Web.Mvc;
using System.Collections.Generic;
using System;

namespace Progra_Avanzada_Proyecto.Controllers
{
    public class InventarioController : Controller
    {
        private readonly HttpClient client = new HttpClient
        {
            BaseAddress = new Uri("https://localhost:44356/api/")
        };

        // GET: Inventario
        public async Task<ActionResult> Index()
        {
            List<InventarioViewModel> inventario = new List<InventarioViewModel>();
            HttpResponseMessage response = await client.GetAsync("Inventarios");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                inventario = JsonConvert.DeserializeObject<List<InventarioViewModel>>(jsonString);
            }
            return View(inventario);
        }

        // GET: Inventario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(InventarioViewModel inventario)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await client.PostAsJsonAsync("Inventarios", inventario);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(inventario);
        }

        // GET: Inventario/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            InventarioViewModel inventario = null;
            HttpResponseMessage response = await client.GetAsync($"Inventarios/{id}");
            if (response.IsSuccessStatusCode)
            {
                inventario = await response.Content.ReadAsAsync<InventarioViewModel>();
            }
            return View(inventario);
        }

        // POST: Inventario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, InventarioViewModel inventario)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await client.PutAsJsonAsync($"Inventarios/{id}", inventario);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(inventario);
        }

        // GET: Inventario/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await client.DeleteAsync($"Inventarios/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Progra-Avanzada-Proyecto/Progra-Avanzada-Proyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - R&R Catering Service</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Themeforest Template Polo, html template">
    <link rel="icon" type="image/png" href="~/images/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Document title -->
    <title>RyR Gastronomía sin Límites</title>
    <!-- Stylesheets & Fonts -->
    <link href="~/css/plugins.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" data-transparent="false" data-fullwidth="true" class="dark submenu-light">
        <div class="header-inner">
            <div class="container">
                <!--Logo-->
                <div id="logo">
                    <a href="@Url.Action("Index", "Home")">
                        <span class="logo-dark">R&R Catering Service</span>
                    </a>
                </div>
                <!--End: Logo-->
                <!--Navigation Resposnive Trigger-->
                <div id="mainMenu-trigger">
                    <a class="lines-button x"><span class="lines"></span></a>
                </div>
                <!--end: Navigation Resposnive Trigger-->
                <!--Navigation-->

                <div id="mainMenu">
                    <div class="container">
                        <nav>
                            <ul>
                                <!-- Enlaces comunes a todos los usuarios -->
                                <li><a href="@Url.Action("Index", "Home")">Inicio</a></li>

                                <!-- Enlaces específicos para el administrador -->
                                @if (Session["Rol"] != null && Session["Rol"].ToString() == "Admin")
                                {
                                    <li><a href="@Url.Action("Index", "Empleados")">Empleados</a></li>
                                    <li><a href="@Url.Action("Index", "Eventos")">Eventos</a></li>
                                    <li><a href="@Url.Action("Index", "Clientes")">Clientes</a></li>
                                    <li><a href="@Url.Action("Index", "Inventario")">Inventario</a></li>
                                    <li><a href="@Url.Action("Index", "Productos")">Productos</a></li>
                                    <li><a href="@Url.Action("Index", "Usuarios")">Usuarios</a></li>
                                    <li><a href="@Url.Action("Logout", "Account")">Cerrar sesión</a></li>
                                }

                                <!-- Enlaces para usuarios autenticados -->
                                @if (Session["Rol"] != null && Session["Rol"].ToString() == "User")
                                {
                                    <li><a href="@Url.Action("Create", "Eventos")">Solicitar evento</a></li>
                                    <li><a href="@Url.Action("Logout", "Account")">Cerrar sesión</a></li>
                                }
                                @if (Session["Rol"] == null)
                                {
                                    <li><a href="@Url.Action("Index", "Account")">Iniciar sesión</a></li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
                <!--end: Navigation-->
            </div>
    </header>
    @RenderBody()

    <footer id="footer">
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="widget">
                        <div class="widget-title">Contáctanos</div>
                        <p>Puedes encontrarnos en:</p>
                        <p>Tacares, Grecia, Alajuela, Costa Rica<br>Teléfono:+506 8507 3503<br>Email: r.rcatering@ryrcateringservice.com</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="widget">
                        <div class="widget-title">Redes Sociales</div>
                        <ul class="list">
                            <li><a href="https://www.instagram.com/ryrgastronomia_/?hl=es">Instagram</a></li>
                            <li><a href="https://es-la.facebook.com/RYRCateringService/">Facebook</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-content">
        <div class="container">
            <div class="copyright-text text-center">&copy; 2023 por RyR Gastronomía sin Límites. - Todos los derechos reservados.</div>
        </div>
    </div>
    </footer>


    <script src="~/js/jquery.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/functions.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>